name: Setup

on:
  workflow_call:
    inputs:
      version:
        description: 'PHP version'
        required: true
        type: string
      ts:
        description: 'Thread Safe'
        required: true
        type: string
        default: 'nts'
      repo:
        description: 'Extension repo'
        required: true
        type: string
      arch:
        description: 'Architecture'
        required: true
        type: string
        default: 'x64'

jobs:
  setup:
    runs-on: windows-2019
    steps:
      - name: Cache PHP SDK
        id: cache-php-sdk
        uses: actions/cache@v3
        with:
          path: |
            php-sdk
            php-dev
            php-bin
          key: setup-php-sdk-${{inputs.version}}-${{inputs.ts}}-${{inputs.arch}}

      - name: Setup PHP
        if: ${{ steps.cache-php-sdk.outputs.cache-hit != 'true' }}
        id: setup-php
        uses: cmb69/setup-php-sdk@v0.7
        with:
          version: ${{inputs.version}}
          arch: ${{inputs.arch}}
          ts: ${{inputs.ts}}

      - name: Compute toolset version
        shell: pwsh
        id: toolset
        run: |
          $toolsets = @{
              "vc14" = "14.0"
          }
          $dir = vswhere -latest -find "VC\Tools\MSVC"
          foreach ($toolset in (Get-ChildItem $dir)) {
              $tsv = "$toolset".split(".")
              if ((14 -eq $tsv[0]) -and (9 -ge $tsv[1])) {
                  $toolsets."vc14" = $toolset
              } elseif ((14 -eq $tsv[0]) -and (19 -ge $tsv[1])) {
                  $toolsets."vc15" = $toolset
              } elseif ((14 -eq $tsv[0]) -and (29 -ge $tsv[1])) {
                  $toolsets."vs16" = $toolset
              } elseif (14 -eq $tsv[0]) {
                  $toolsets."vs17" = $toolset
              }
          }
          $toolset = $toolsets."vs16"
          
          Add-Content $Env:GITHUB_PATH "$pwd\php-sdk\bin"
          Add-Content $Env:GITHUB_PATH "$pwd\php-sdk\msys2\usr\bin"
          Add-Content $Env:GITHUB_PATH "$pwd\php-bin"
          Add-Content $Env:GITHUB_PATH "$pwd\php-dev"
          Write-Output "toolset=$toolset" >> $Env:GITHUB_OUTPUT
          Write-Output "prefix=$pwd\php-bin" >> $Env:GITHUB_OUTPUT
          Write-Output "vs=vs16" >> $Env:GITHUB_OUTPUT

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{inputs.arch}}
          toolset: ${{steps.toolset.outputs.toolset}}

      - name: Get Extension Source
        run: |
          git clone https://github.com/${{inputs.repo}} ext
