name: "Parallel"
on:
  workflow_dispatch:
  schedule:
    - cron: "10 1 * * 4"
jobs:
  build:
    name: Build
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        version: ["8.0", "8.1", "8.2"]
        ts: ["ts"]
        arch: ["x64"]
        name: ["parallel"]
        repo: ["krakjoe/parallel"]
        enable: ["with-parallel"]
        release: ["Release_TS"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Builder
        uses: ./.github/actions/build
        with:
          version: ${{ matrix.version }}
          ts: ${{ matrix.ts }}
          arch: ${{ matrix.arch }}
          repo: ${{ matrix.repo }}
          enable: ${{ matrix.enable }}
          name: ${{ matrix.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
