name: 'Pcov'
on:
  workflow_dispatch:
  schedule:
    - cron: '27 9 * * 4'
jobs:
  build:
    name: build
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0', '8.1', '8.2', '8.3' ]
        ts: [ ts, nts ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        # script parameters $extension $repo $branch $dev_branch $args $sdk_version $vs $arch $ts $php
        run: |
          pwsh scripts/builder.ps1 pcov krakjoe/pcov release develop enable-pcov master vs16 x64 ${{ matrix.ts }} ${{ matrix.php }}
          $exit_code = $?
          if(-not($exit_code)) {
            exit $exit_code
          }
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: pcov_${{ matrix.ts }}_x64
          path: pcov
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - run: mkdir ext
      - uses: actions/download-artifact@v3
        name: Download Artifacts
        with:
          path: ext
      - name: Release
        run: |
          set -x
          assets=()
          for asset in ./ext/*/*.dll; do
            assets+=("$asset")
          done
          if ! gh release view pCov; then
            gh release create "pCov" "${assets[@]}" -t "pCov" -n "pCov"
          else
            gh release upload "pCov" "${assets[@]}" --clobber
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
