name: "Tensor"
on:
  workflow_dispatch:
  schedule:
    - cron: "50 1 * * 4"
jobs:
  build:
    name: Build
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        version: ["8.2"]
        ts: ["ts", "nts"]
        arch: ["x64"]
        name: ["tensor"]
        repo: ["RubixML/Tensor"]
        enable: ["enable-tensor"]
        include:
          - ts: "ts"
            release: "Release_TS"
          - ts: "nts"
            release: "Release"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Builder
        uses: ./.github/actions/build-tensor
        with:
          version: ${{ matrix.version }}
          ts: ${{ matrix.ts }}
          arch: ${{ matrix.arch }}
          repo: ${{ matrix.repo }}
          enable: ${{ matrix.enable }}
          name: ${{ matrix.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
