name: 'Tensor'
on:
  workflow_dispatch:
jobs:
  build:
    name: build
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0', '8.1' ]
        ts: [ ts, nts ]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        # script parameters $extension $repo $branch $dev_branch $args $sdk_version $vs $arch $ts $php
        run: |
          pwsh scripts/tensor.ps1 tensor RubixML/Tensor master master enable-tensor master vs16 x64 ${{ matrix.ts }} ${{ matrix.php }}
          $exit_code = $?
          if(-not($exit_code)) {
            exit $exit_code
          }
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: tensor_${{ matrix.ts }}_x64
          path: tensor
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - run: mkdir ext
      - uses: actions/download-artifact@v2
        with:
          path: ext
      - name: Release
        run: |
          set -x
          assets=()
          for asset in ./ext/*/*.dll; do
            assets+=("$asset")
          done
          if ! gh release view Tensor; then
            gh release create "Tensor" "${assets[@]}" -t "Tensor" -n "Tensor"
          else
            gh release upload "Tensor" "${assets[@]}" --clobber
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
