name: "Trader"
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "27 9 * * 4"
jobs:
  build:
    name: Build
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        version: ["8.0", "8.1", "8.2"]
        ts: ["ts", "nts"]
        arch: ["x64"]
        name: ["trader"]
        repo: ["php/pecl-math-trader"]
        enable: ["enable-trader"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        id: setup-php
        uses: cmb69/setup-php-sdk@v0.7
        with:
          version: ${{matrix.version}}
          arch: ${{matrix.arch}}
          ts: ${{matrix.ts}}
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: ${{steps.setup-php.outputs.toolset}}
      - name: Get Extension Source
        run: |
          git clone https://github.com/${{matrix.repo}} ext
      - name: Build Extension
        run: |
          cd ext
          phpize
          ./configure --${{matrix.enable}} --with-prefix=${{steps.setup-php-sdk.outputs.prefix}}
          nmake
      - name: Upload Extension
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.name}}-${{matrix.version}}-${{matrix.ts}}-${{matrix.arch}}
          path: ext/x64/**/*.dll
