name: "Trader"
on:
  workflow_dispatch:
  schedule:
    - cron: "27 9 * * 4"
jobs:
  build:
    name: Build
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        version: ["8.0", "8.1", "8.2"]
        ts: ["ts", "nts"]
        arch: ["x64"]
        name: ["trader"]
        repo: ["php/pecl-math-trader"]
        enable: ["enable-trader"]
        include:
          - ts: "ts"
            release: "Release_TS"
          - ts: "nts"
            release: "Release"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        id: setup-php
        uses: cmb69/setup-php-sdk@v0.7
        with:
          version: ${{matrix.version}}
          arch: ${{matrix.arch}}
          ts: ${{matrix.ts}}
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: ${{steps.setup-php.outputs.toolset}}
      - name: Get Extension Source
        run: |
          git clone https://github.com/${{matrix.repo}} ext
      - name: Build Extension
        run: |
          cd ext
          phpize
          ./configure --${{matrix.enable}} --with-prefix=${{steps.setup-php-sdk.outputs.prefix}}
          nmake
      - name: Package Extension
        run: |
          md .install
          copy ext\${{matrix.arch}}\${{matrix.release}}\php_${{matrix.name}}.dll .install\php${{matrix.version}}_${{matrix.ts}}_${{matrix.arch}}_${{matrix.name}}.dll
      - name: Upload Extension
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.name}}-${{matrix.version}}-${{matrix.ts}}-${{matrix.arch}}
          path: .install
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - run: mkdir ext
      - uses: actions/download-artifact@v3
        name: Download Artifacts
        with:
          path: ext
      - name: Release
        run: |
          set -x
          assets=()
          for asset in ./ext/*/*.dll; do
            assets+=("$asset")
          done
          if ! gh release view Trader; then
            gh release create "Trader" "${assets[@]}" -t "Trader" -n "Trader"
          else
            gh release upload "Trader" "${assets[@]}" --clobber
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
